site_title: Sabrina Hanapiah, Front End Web Developer
author_first_name: Sabrina
author_last_name: Hanapiah
email: sabrinahanapiah@gmail.com
location: Brooklyn, NY
role: Front End Web Developer
title: Hi, I'm Sabrina.
sub-title: I'm a front-end web developer.
description: I have a passion for coding beautiful, intuitive websites that people love to use.
email: sabrinahanapiah@gmail.com

# social links
twitter: https://twitter.com/sabbygee
instagram: https://instagram.com/sabrinahanapiah
github:  https://github.com/sabrinahanapiah
rss: rss

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings

plugins:

include:
  - "_img"
